#+title: Config
#+Author: Ethan Beyl

* Table of Contents :toc:
- [[#todos-01][TODOS]]
- [[#packages][Packages]]
  - [[#useful-snippets][Useful Snippets]]
- [[#config][Config]]
  - [[#original-config-need-to-fix][Original Config (Need to fix)]]
  - [[#git-auto-fetch][Git Auto Fetch]]
  - [[#insert-tree][Insert Tree]]
  - [[#treemacs-keybind][Treemacs Keybind]]
  - [[#make-org-headers-look-nicer][Make Org headers look nicer]]
  - [[#merge-conflict-buttons][Merge Conflict Buttons]]
  - [[#org-roam-ui][Org-Roam-UI]]
- [[#features-to-implement][Features to Implement]]
  - [[#orderless][Orderless]]
  - [[#look-into-denote-for-note-management][Look Into Denote for Note Management]]
  - [[#combobulate][Combobulate]]

* TODOS [0/1]
- [ ] Clean up the config to be easier to navigate and read.

* Packages
#+begin_src emacs-lisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
(package! magit-todos)
(package! git-gutter)
(package! tldr)
(package! leetcode)
(package! conflict-buttons)

;;; We do this so that org-roam-ui will work properly since it wants the most recent version of org-roam but doom wants strict version control
(unpin! org-roam)
(package! org-roam-ui)

;; Unity Integration Package
(straight-use-package
 '(unity :type git :host github :repo "elizagamedev/unity.el"))
(add-hook 'after-init-hook #'unity-mode)


;; Quickshell LSP support
;;(use-package qml-ts-mode
;;  :after lsp-mode
;;  :config
;;  (add-to-list 'lsp-language-id-configuration '(qml-ts-mode . "qml-ts"))
;;  (lsp-register-client
;;   (make-lsp-client :new-connection (lsp-stdio-connection '("qmlls"))
;;                    :activation-fn (lsp-activate-on "qml-ts")
;;                    :server-id 'qmlls))
;;  (add-hook 'qml-ts-mode-hook (lambda ()
;;                                (setq-local electric-indent-chars '(?\n ?\( ?\) ?{ ?} ?\[ ?\] ?\; ?,))
;;                                (lsp-deferred))))

#+end_src
** Useful Snippets
#+begin_src emacs-lisp
;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;; (package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;; (package! another-package
;;   :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;; (package! this-package
;;   :recipe (:host github :repo "username/repo"
;;            :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;; (package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;; (package! builtin-package :recipe (:nonrecursive t))
;; (package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;; (package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;; (package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;; (unpin! pinned-package)
;; ...or multiple packages
;; (unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;; (unpin! t)

#+end_src
* Config
** Original Config (Need to fix)
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el --- Summary: My Doom emacs config -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(setq doom-theme 'doom-spacegrey)
(setq doom-font (font-spec :family "JetBrainsMono NF" :size 14))

(setq display-line-numbers-type 'relative)

;;; Set org directory
(setq org-directory "~/org/")
(setq org-agenda-files '("~/org/"))

(after! org
  (add-to-list 'org-capture-templates
               '("e" "Event / Appointment" entry
                 (file "~/org/calendar.org")
                 "* TODO %^{Task Name}\nSCHEDULED: %^t\n%?"
                 :empty-lines 1)
               ))
(after! org
  (add-to-list 'org-capture-templates
               '("i" "Idea" entry
                 (file "~/org/ideas.org")
                 "* IDEA %?"
                 :empty-lines 1)
               ))

(after! org-roam
  (setq org-roam-capture-templates
        '(("a" "atomic note" plain
           "%?"
           :if-new (file+head "atoms/${slug}.org" "#+title: ${title}\n")
           :unnarrowed t)

          ("s" "school notebook" plain
           "%?"
           :if-new (file+head "school/${slug}.org" "#+title: ${title}\n#+filetags: :school:\n")
           :unnarrowed t)

          ("p" "project" plain
           "%?"
           :if-new (file+head "projects/${slug}.org" "#+title: ${title}\n#+filetags: :project:\n")
           :unnarrowed t))))

;; Adds leetcode support
(use-package! leetcode
  :config
  ;; LeetCode supports Racket and Scheme for Lisp-family languages
  (setq leetcode-prefer-language "racket")
  (setq leetcode-save-solutions t)
  (setq leetcode-directory "~/Dev/Leetcode"))

;; Stops doom from interfering with the leetcode popups
(set-popup-rule! "^\\*leetcode" :ignore t)

;; Adds TODO tracking in git page so we can see TODOs in git repos and per branch
(use-package! magit-todos
  :after magit
  :config
  (magit-todos-mode 1))

;; Add git gutters
(use-package! git-gutter
  :hook (find-file . git-gutter-mode)
  :config
  (setq git-gutter:update-interval 0.02)
  ;; Force colors so the theme doesn't overwrite them
  (custom-theme-set-faces! 'user
    '(git-gutter:added :foreground "green" :weight bold)
    '(git-gutter:deleted :foreground "red" :weight bold)
    '(git-gutter:modified :foreground "yellow" :weight bold)))

;; Add Unity Mode to emacs for opening files with unity
(straight-use-package
 '(unity :type git :host github :repo "elizagamedev/unity.el"))
(add-hook 'after-init-hook #'unity-mode)

;; Used for adding Unity LPS suggestions
(use-package lsp-mode
  :ensure t
  :bind-keymap
  ("C-c l" . lsp-command-map)
  :custom
  (lsp-keymap-prefix "C-c l"))

(use-package csharp-mode
  :ensure t
  :init
  (defun my/csharp-mode-hook ()
    (setq-local lsp-auto-guess-root t)
    (lsp))
  (add-hook 'csharp-mode-hook #'my/csharp-mode-hook))

(map! :leader
      :desc "Git stage hunk"
      "g s" #'git-gutter:stage-hunk)
(setq confirm-kill-emacs nil)


;; Setup vshell and make it use fish
;; Keep a POSIX shell for background Emacs subprocesses to prevent errors
(setq shell-file-name (executable-find "bash"))

;; Explicitly force interactive terminals (vterm) to use Fish shell
(setq-default vterm-shell (executable-find "fish"))
(setq-default explicit-shell-file-name (executable-find "fish"))

;; Set different font sizes for Org Mode Headers
(custom-set-faces!
  '(org-level-1 :inherit outline-1 :height 1.5 :weight bold)
  '(org-level-2 :inherit outline-2 :height 1.4 :weight bold)
  '(org-level-3 :inherit outline-3 :height 1.3 :weight bold)
  '(org-level-4 :inherit outline-4 :height 1.2 :weight bold)
  '(org-level-5 :inherit outline-5 :height 1.1 :weight bold)
  '(org-document-title :height 1.8 :bold t :underline nil))
#+end_src

#+RESULTS:
| doom--customize-themes-h-1042 | doom--customize-themes-h-1043 | doom--customize-themes-h-1044 | doom--customize-themes-h-1045 |

** Git Auto Fetch
This is a custom plugin I've been working on to autosync git repositories when you enter them. It would be inefficient however, to fetch each time you enter a new repo since it would happen frequently. Instead it will check on a configurable interval, and log it's latest check for each repository in a file. If the repository was recently fetched. We won't fetch it, but you still can manually fetch if you'd like.

#+begin_src emacs-lisp
;;; git-auto-fetch.el --- Auto-fetch git repositories -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(defvar git-auto-fetch/repos nil
  "Alist storing repository preferences and timestamps.
Format: ((\"/path/to/repo/\" AUTO-FETCH-BOOLEAN LAST-FETCH-TIME) ...)")

(defvar git-auto-fetch/last-repo nil
  "Tracks the last visited git repository to prevent duplicate checks.")

(defvar git-auto-fetch/cooldown 3600
  "Seconds to wait before fetching the same repo again (3600 = 1 hour).")

;; Persist the alist across Emacs sessions using Doom's built-in session manager
(with-eval-after-load 'savehist
  (add-to-list 'savehist-additional-variables 'git-auto-fetch/repos))

(defun git-auto-fetch/do-fetch (repo)
  "Run git fetch asynchronously in the background for REPO."
  (message "Auto-fetching repo: %s" repo)
  (let ((default-directory repo))
    (magit-run-git-async "fetch" "--all" "--quiet")))

(defun git-auto-fetch/check-for-repo ()
  "Check repository state, handle cooldowns, or prompt if unknown."
  (let ((current-repo (magit-toplevel)))
    (when (and current-repo
               (not (equal current-repo git-auto-fetch/last-repo)))

      ;; Remember we are here to avoid spamming on every subsequent file open
      (setq git-auto-fetch/last-repo current-repo)

      (let ((entry (assoc current-repo git-auto-fetch/repos))
            (now (float-time (current-time))))

        (if entry
            ;; Repo is known. Extract the stored data.
            (let ((auto-fetch-enabled (nth 1 entry))
                  (last-fetch-time (nth 2 entry)))

              ;; If auto-fetch is on AND the cooldown has expired
              (when (and auto-fetch-enabled
                         (> (- now last-fetch-time) git-auto-fetch/cooldown))
                (git-auto-fetch/do-fetch current-repo)
                ;; Update memory with new timestamp (shadows the old entry)
                (push (list current-repo t now) git-auto-fetch/repos)))

          ;; Repo is unknown. Prompt the user.
          (let ((choice (completing-read (format "Auto-sync repo %s? " current-repo)
                                         '("yes" "no" "abort") nil t)))
            (cond
             ((string= choice "yes")
              (git-auto-fetch/do-fetch current-repo)
              (push (list current-repo t now) git-auto-fetch/repos))

             ((string= choice "no")
              ;; Save 'no' with a 0 timestamp so it is remembered forever
              (push (list current-repo nil 0) git-auto-fetch/repos))

             ((string= choice "abort")
              (message "Aborted. Will ask again next time.")
              ;; Clear last-repo so it reprompts immediately on the next file open
              (setq git-auto-fetch/last-repo nil)))))))))

;; Attach to file and directory open events
(add-hook 'find-file-hook #'git-auto-fetch/check-for-repo)
(add-hook 'dired-mode-hook #'git-auto-fetch/check-for-repo)

(provide 'git-auto-fetch)
;;; git-auto-fetch.el ends here
#+end_src

** Insert Tree
#+begin_src emacs-lisp
(defun insert-tree ()
  "Inserts a Tree for a given directory"
  (interactive)
  (let* ((directory-to-tree (read-string "Directory to Tree: "))
         (tree-depth (read-number "Enter Depth: "))
         (tree-command (format "tree %s -L %d" directory-to-tree tree-depth))
         (tree-string (shell-command-to-string tree-command)))
    (insert tree-string)))

(map! :leader
      :desc "Insert Filetree"
      "i t" #'insert-tree)
#+end_src

** Treemacs Keybind
I wanted to keep my FileTree on the left side to quickly navigate project files outside of having to go to the file explorer buffer each time. Doom Emacs has a built in function for this called treemacs.
#+begin_src emacs-lisp
(map! :leader
      :desc "Toggle Treemacs File Explorer"
      "e e" #'treemacs)
#+end_src
** Make Org headers look nicer
#+begin_src emacs-lisp
(after! org-modern
  (setq org-modern-star '("◉" "○" "✿" "✸" "✤" "✜" "◆" "▶")))
#+end_src

#+RESULTS:
| ◉ | ○ | ✿ | ✸ | ✤ | ✜ | ◆ | ▶ |
** Merge Conflict Buttons
#+begin_src emacs-lisp
(use-package! conflict-buttons
  :hook (find-file . conflict-buttons-mode))
#+end_src

#+RESULTS:
| tramp-set-connection-local-variables-for-buffer | conflict-buttons-mode | gdb-find-file-hook | undo-fu-session--recover-safe | recentf-track-opened-file | projectile-find-file-hook-function | persp-add-or-not-on-find-file | org-roam-db-autosync--setup-file-h | auto-revert-find-file-function | git-commit-setup-check-buffer | doom-modeline-update-persp-name | doom-modeline-update-vcs | doom-modeline-update-buffer-file-name | doom-modeline-update-buffer-file-icon | doom-modeline-update-env | git-auto-fetch/check-for-repo | url-handlers-set-buffer-mode | git-gutter-mode | +vc-init-smerge-mode-h | epa-file-find-file-hook | vc-refresh-state | save-place-find-file-hook |

** Org-Roam-UI
Adds a pretty graph view for emacs roam files. Like Obsidian but emacs.
#+begin_src emacs-lisp
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src
* Features to Implement
** Orderless
Allows you to search for functions like `org-export-dispatch-to-pdf` by just typing `org pdf export`
** Look Into Denote for Note Management
[[https://github.com/protesilaos/denote]]
** Combobulate
Uses TreeSitter to allow you to edit and move code around easier than other methods by understanding the syntax of the code so when you move a block it avoids other blocks
