exec-once = swww-daemon     # Starts Wallpaper daemon
exec-once = swww restore    # Sets the last used wallpaper
exec-once = hypridle	    # Starts the idle daemon


exec-once = waybar  # Start Waybar
exec-once = swaync --style ~/.dotfiles/configs/swaync/style.css   # Start Notifcation Center
