exec-once = hypridle	    # Starts the idle daemon
exec-once = hyprlock        # Open lock screen on start
exec-once = udiskie         # Starts USB drive daemon
exec-once = hyprpaper       # Used for wallpaper


exec-once = quickshell      # Startquickshell
exec-once = emacs --daemon  # Emacs is always open

exec-once = hyprctl setcursor BreezeX-RosePine # Sets cursor to rose pine
