exec-once = hypridle	    # Starts the idle daemon
# exec-once = hyprlock
exec-once = udiskie         # Starts USB drive daemon
exec-once = hyprctl setcursor BreezeX-RosePine # Sets cursor to rose pine
exec-once = hyprpaper



exec-once = waybar  # Start Waybar
exec-once = swaync --style ~/.dotfiles/configs/swaync/style.css   # Start Notifcation Center
