$wallpaper = /home/ebeyl/.dotfiles/wallpapers/nasa.png
$background = 1a1110
$foreground = f1dfdb

$primary = ffb4a7
$secondary = e7bdb5
$tertiary = ddc48c
$surface = 1a1110
$surface_bright = 423735
$outline = a08c89
$error = 000000

$shadow = 000000
