$wallpaper = /home/ebeyl/.dotfiles/wallpapers/nasa.png
$background = 1a120e
$foreground = f0dfd8

$primary = ffb690
$secondary = e6beab
$tertiary = cec890
$surface = 1a120e
$surface_bright = 413732
$outline = a08d84
$error = 000000

$shadow = 000000
